version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_drupal
      - MARIADB_DATABASE=bitnami_drupal
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  drupal:
    build: .
    container_name: drupal
    environment:
      - DRUPAL_DATABASE_HOST=mariadb
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=bn_drupal
      - DRUPAL_DATABASE_NAME=bitnami_drupal
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DRUPAL_PASSWORD=${PASSWORD}
    volumes:
      - 'drupal_data:/bitnami/drupal'
    depends_on:
      - mariadb
  onlyoffice-document-server:
    restart: unless-stopped
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-document-server
    environment:
      - ${JWT_ENV}
  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../common/nginx_conf/local.conf:/etc/nginx/local.conf
      - ../common/nginx_conf/map.conf:/etc/nginx/map.conf
      - ../common/nginx_conf/${NGINX_CONF}:/etc/nginx/nginx.conf
      - ./app.conf:/etc/nginx/app.conf
      - /etc/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - drupal
volumes:
  mariadb_data:
    driver: local
  drupal_data:
    driver: local
