version: '3'
services:
  moodle:
    image: docker.io/bitnami/moodle:4.5
    container_name: app-server
    # ports:
    #  - 8080:8080
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_REVERSEPROXY=true
      - MOODLE_SSLPROXY=${SSL_PROXY}
       # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
      - MOODLE_USERNAME=user
      - MOODLE_PASSWORD=${PASSWORD}
      - MOODLE_HOST=${APP_ADDR}
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
      - ./onlyoffice:/tmp/onlyoffice
      - ./run.sh:/run.sh
    networks:
      - onlyoffice
    depends_on:
      - mariadb
    command: bash /run.sh

  mariadb:
    image: docker.io/bitnami/mariadb:11.1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - onlyoffice

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:${DS_TAG}
    restart: always
    environment:
      - ${JWT_ENV}
    networks:
      - onlyoffice
    ports:
      - 3000:80
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - onlyoffice
    volumes:
      - ./${NGINX_CONF}:/etc/nginx/nginx.conf
      - ../common/nginx_conf/local.conf:/etc/nginx/local.conf
      - ../common/nginx_conf/map.conf:/etc/nginx/map.conf
      - ./app.conf:/etc/nginx/app.conf
      - /etc/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - moodle


networks:
  onlyoffice:
    driver: 'bridge'
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
  document_data:
    driver: local
  document_log:
    driver: local
