version: '3'
services:
  mariadb:
    container_name: mariadb
    image: docker.io/bitnami/mariadb:10.3
    restart: always
    networks:
      - onlyoffice
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/bitnami/mariadb
    depends_on:
      - onlyoffice-document-server
  app:
    container_name: app-server
    image: bitnami/moodle
    restart: always
    ports:
      - 80
      - 443
    networks:
      - onlyoffice
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      #- MOODLE_USERNAME='user'
      #- MOODLE_PASSWORD='bitnami'
      #- MOODLE_EMAIL='user@example.com'
      #- MOODLE_SITE_NAME='New Site'
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
      - ./onlyoffice:/tmp/onlyoffice
      - ./run.sh:/run.sh
    command: bash /run.sh
    depends_on:
      - mariadb
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    expose:
      - 80
      - 443
    networks:
      - onlyoffice
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - onlyoffice
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../common/nginx_conf/local.conf:/etc/nginx/local.conf
      - ../common/nginx_conf/map.conf:/etc/nginx/map.conf
    depends_on:
      - app
networks:
  onlyoffice:
    driver: 'bridge'
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
  document_data:
    driver: local
  document_log:
    driver: local
