pipeline {
  agent {label 'ubuntu'}
  options {
    disableConcurrentBuilds()
    buildDiscarder (logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
  }  
  parameters {
    choice(name: 'Connector', choices: ['humhub','alfresco/standalone','chamilo'], description: '')
    string(name: 'st', defaultValue: 'latest', description: '-st, service_tag. Default: latest')
    string(name: 'cu', defaultValue: 'from_pipeline', description: '-cu, connector_url. Add custom url or will be used url from pipeline.')
    booleanParam (name:'EXECUTE', defaultValue: true, description: 'Run this item ?')
  }
    
  stages {
    stage ('Delete old VM') {
      when { expression { return env.EXECUTE == "true" } }
      steps {
        withCredentials([string(credentialsId: 'do_install_connector', variable: 'DO_TOKEN')]) {
          sh '''
            echo "Old VMs were deleted."
          '''
        }
      }
    }
    stage ('Create VM with connector') {
      when { expression { return env.EXECUTE == "true" } }
      steps {
        withCredentials([ string(credentialsId: 'do_install_connector', variable: 'DO_TOKEN'),
                          usernamePassword(credentialsId: 'gitrobot_token', 
                            usernameVariable: 'GIT_USER',
                            passwordVariable: 'GIT_TOKEN'), ]) 
        {
          sh '''
            #!/usr/bin/env bash

            if [[ ${Connector} == "humhub" ]]; then
              if [[ ${cu} == "from_pipeline" ]]; then
                connector_url='https://github.com/ONLYOFFICE/onlyoffice-humhub/releases/download/v2.4.0/onlyoffice.zip'
              else
                connector_url=${cu}
              fi

              bash .jenkins/connector_install.sh ${Connector} ${connector_url} 
            fi
            
            echo "Connector ${Connector} created."
          '''
        }
      }
    }
  }
}
