version: '3'
services:
  frontend:
    image: plone/plone-frontend:latest
    container_name: frontend
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    ports:
      - "3000:3000"
    networks:
      - onlyoffice
    depends_on:
      - backend

  backend:
    image: plone/plone-backend:${SERVICE_TAG}
    container_name: backend
    environment:
      SITE: Plone
      CORS_ALLOW_ORIGIN: "*"
      CORS_ALLOW_CREDENTIALS: "true"
      DEVELOP: "/app/src/onlyoffice.plone"
      #ADDONS: "onlyoffice.plone"
    volumes:
      - /connectors/onlyoffice:/app/src/onlyoffice.plone
    ports:
      - "8080:8080"
    networks:
      - onlyoffice
        #    expose:
        #      - 8080
    depends_on:
      - db
    healthcheck:
      test: nc -z -w5 127.0.0.1 8080 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver
    restart: always
    environment:
      - ${JWT_ENV}
    networks:
      - onlyoffice
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - onlyoffice
    volumes:
      - ../common/nginx_conf/local.conf:/etc/nginx/local.conf
      - ../common/nginx_conf/map.conf:/etc/nginx/map.conf
      - ./${NGINX_CONF}:/etc/nginx/nginx.conf
      - /etc/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
networks:
  onlyoffice:
    driver: 'bridge'
volumes:
  document_data:
  document_log:
